#!/usr/bin/env node
/* NOGGIN — bundler. Zero dependencies, no toolchain.

   Inlines src/*.js into index.html to produce a single self-contained file.

     node build.js                 -> play.html   (standalone document)
     node build.js --fragment out  -> a body-only fragment, for hosts that
                                      supply their own document shell

   The bundle is generated, never hand-edited: index.html and src/ stay the
   only source of truth. */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

/* Pull the script sources out in document order so the bundle preserves the
   dependency order the page relies on. */
const scriptTag = /<script\s+src="([^"]+)"\s*><\/script>/g;
const sources = [];
let m;
while ((m = scriptTag.exec(html)) !== null) sources.push(m[1]);
if (!sources.length) throw new Error('no <script src> tags found in index.html');

const bundle = sources.map(function (src) {
  const code = fs.readFileSync(path.join(ROOT, src), 'utf8');
  return '/* ===== ' + src + ' ===== */\n' + code.trim();
}).join('\n\n');

function section(re, label) {
  const found = html.match(re);
  if (!found) throw new Error('could not find ' + label + ' in index.html');
  return found[1];
}

const style = section(/<style>([\s\S]*?)<\/style>/, '<style> block');
const title = section(/<title>([\s\S]*?)<\/title>/, '<title>');
const body = section(/<body>([\s\S]*?)<\/body>/, '<body>')
  .replace(scriptTag, '')
  .trim();

const banner = '<!-- NOGGIN - generated by build.js, do not edit directly. -->';
const inline = '<script>\n' + bundle + '\n</script>';

const args = process.argv.slice(2);
const fragmentIndex = args.indexOf('--fragment');

let out, text;
if (fragmentIndex !== -1) {
  out = args[fragmentIndex + 1];
  if (!out) throw new Error('--fragment requires an output path');
  text = [banner, '<title>' + title + '</title>', '<style>' + style + '</style>', body, inline].join('\n');
} else {
  out = args[0] || path.join(ROOT, 'play.html');
  text = [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover">',
    '<meta name="color-scheme" content="dark">',
    '<title>' + title + '</title>',
    banner,
    '<style>' + style + '</style>',
    '</head>',
    '<body>',
    body,
    inline,
    '</body>',
    '</html>'
  ].join('\n');
}

fs.writeFileSync(out, text);
process.stdout.write('wrote ' + out + '  (' + (text.length / 1024).toFixed(1) + ' KB, ' +
  sources.length + ' modules inlined)\n');
