var SCENES=[
    {n:1,t:'Before Anyone Is Awake',d:50,c:[[2,"Every morning, in every country on earth, something happens that no one records."],[10,"Millions of people get up and do what they said they would do."],[18,"No ceremony. No audience."],[25,""],[33,"What if one of civilization's greatest foundations has been hiding in plain sight?"]]},
    {n:2,t:'The Ordinary',d:50,c:[[1,"A welder, whose seam will hold a bridge for sixty years."],[9,"A father, learning a patience nobody taught him."],[18,"A teacher who stays late for one student who did not ask him to."],[27,"A researcher whose work will not be finished in his lifetime."],[36,"A son sitting with his mother in a room where nothing can be fixed."],[43,"Civilization is carried by the ordinary, repeated across billions of days."]]},
    {n:3,t:'What This Is, And What It Is Not',d:40,c:[[1,"This film is about men."],[5,"It is not an argument that men matter more than women."],[12,"That argument is false, and this film has no use for it."],[19,"It is an argument about a structure —"],[24,"and what happens when one of its load-bearing members is left unmaintained."],[32,"The question is what a civilization requires in order to keep standing."]]},
    {n:4,t:'The Word',d:45,c:[[1,"Integrity comes from the Latin integer — whole, untouched, undivided."],[11,"The same word a mathematician uses for a number that is not a fraction."],[20,"The same word an engineer uses for a beam that has not been compromised."],[29,"Before integrity was a virtue, it was a description."],[35,"Integrity is not a claim of goodness. It is a condition of wholeness."]]},
    {n:5,t:'Ten Ways To Be Whole',d:55,c:[[1,"A human being is whole in more than one dimension."],[8,"Biological. Neurological. Psychological."],[15,"Emotional — the capacity to feel accurately."],[21,"Ethical and moral — what you believe, matching what you actually do."],[28,"Relational — the ability to be trusted, and to trust."],[34,"Occupational. Environmental."],[40,"And sovereign — remaining the author of your own life."],[46,"Damage any one of them, and the others begin to carry its weight."]]},
    {n:6,t:'Every Decision Passes Through A Body',d:50,c:[[1,"Every ethical decision a person makes passes through an organism."],[8,"Judgment runs on a prefrontal cortex."],[14,"Emotional regulation runs on a nervous system that can be exhausted."],[22,"Empathy runs on circuits that pain, fear and inflammation can narrow."],[30,"Hormones do not issue commands. They set the terms."],[37,"None of this makes a man good."],[42,"All of it determines what he has to work with."]]},
    {n:7,t:'The Unglamorous Things',d:45,c:[[1,"So the unglamorous things are not incidental."],[6,"Sleep restores the link between the brain's alarm and what moderates it."],[14,"Take it away, and the alarm gets louder while the moderator gets quieter."],[22,"But be careful. Biology does not guarantee morality."],[28,"Healthy men do terrible things. Sick men do heroic ones."],[35,"It decides how much capacity a man brings to the question."]]},
    {n:8,t:'What We Measure',d:45,c:[[1,"When we measure what happens to men, some numbers repeat almost everywhere."],[9,"Men die earlier."],[13,"They account for most suicides, and for most deaths at work."],[20,"They are less likely to see a doctor before a problem becomes urgent."],[27,"None of this is a competition."],[31,"Women carry burdens these particular numbers do not show."],[38,"But a pattern this consistent is not noise. It is information."]]},
    {n:9,t:'Downstream',d:45,c:[[1,"No organism is separate from the place it lives."],[7,"A river carries whatever the land upstream gives it."],[14,"A lung takes whatever the air is carrying."],[21,"You cannot keep a body healthy inside an environment that is failing."],[30,"Health is not only a property of a person."],[36,"It is a property of a place."]]},
    {n:10,t:'Every Room Teaches',d:45,c:[[1,"Then widen the word environment until it becomes honest."],[7,"A home is an environment. A classroom. A worksite."],[14,"So is a hiring process. So is a courtroom. So is a comment thread."],[22,"These places do not merely surround people."],[27,"They teach."],[32,"Every institution transmits a curriculum it never wrote down."]]},
    {n:11,t:'Cooperation Was Never Free',d:50,c:[[1,"Civilization did not begin because human beings trusted one another."],[8,"It began because they built the machinery that makes trust rational."],[16,"Reciprocity. Reputation. Accountability."],[23,"Norms. Repair. Institutions."],[31,"Take those away, and cooperation does not become difficult."],[39,"It becomes irrational."]]},
    {n:12,t:'The Transfer',d:50,c:[[1,"Most people behave as conditional cooperators."],[6,"They contribute — until they watch others take without giving."],[13,"Then contribution collapses. Not out of malice. Out of arithmetic."],[21,"Every person who keeps their word carries part of the load."],[28,"Remove some of them, and the load does not disappear. It transfers."],[37,"The ones still standing carry more."],[43,"They do not fail immediately. They fatigue."]]},
    {n:13,t:'Trust Is Infrastructure',d:50,c:[[1,"This is why trust is not a mood. It is infrastructure."],[8,"Everything a society builds sits on top of it."],[15,"Fields. Cities. Contracts. Law. Medicine. Bridges. Power grids."],[24,"Integrity lowers the cost of running a civilization."],[30,"Every promise that holds is an audit not performed, a lock not bought."],[39,"Corruption raises that cost — and everybody pays it."]]},
    {n:14,t:'Both Hands',d:45,c:[[1,"Here the film has to be careful."],[5,"Environments shape people. That is true."],[11,"It is also true that a man is responsible for what he does."],[18,"Both hands hold weight."],[24,"An environment that makes integrity expensive does not excuse abandoning it."],[32,"And responsibility does not excuse whoever made integrity expensive."],[39,"Explaining is not excusing."]]},
    {n:15,t:'The Accounting',d:45,c:[[1,"There is a way societies fail men that is easy to miss, because it looks like praise."],[10,"He is valued for what he produces. His output. His income. His usefulness."],[19,"That is not admiration. It is accounting."],[25,"A person valued only for his function has been told what happens when it stops."],[34,"Dignity does not begin at the moment a person becomes useful."],[40,"If it did, it would not be dignity. It would be a wage."]]},
    {n:16,t:'The Gate',d:45,c:[[1,'"Do you want to become a real man?"'],[6,"Look at the structure of that question."],[11,"It presents manhood as a status that must be earned — and can be taken away."],[20,"But a boy does not require certification in order to be male. He already is."],[29,""],[36,"The gate was never real. Somebody has just been charging admission."]]},
    {n:17,t:'Tending',d:40,c:[[1,"Give up the gate, and something better survives it."],[7,"Development."],[11,"Not to prove a claim — because a life is long, and there is work worth being equal to."],[21,"Skill. Patience. Honesty under pressure. Care that nobody sees."],[28,"Nobody graduates from that."],[33,"A man is not a thing to be certified. He is a thing to be tended."]]},
    {n:18,t:'There Was Never A Boundary',d:40,c:[[3,"And what a man tends tends him back."],[8,"A river delta and a set of bronchi solve the same problem with the same shape."],[17,"Caring for a forest, a watershed, a city's air is not masculine or feminine."],[25,"It is human."],[29,"Protect an environment and you are protecting a nervous system."],[35,"There was never a boundary there."]]},
    {n:19,t:'The Return',d:40,c:[[1,"So the boys become men."],[5,"Fathers, or not. Teachers. Builders. Patients. Caregivers."],[13,"Some are strong. Some are tired."],[18,"Some need help and were never taught how to ask."],[24,""],[31,"They are not remarkable."],[35,"They are load-bearing."]]},
    {n:20,t:'Virdignity',d:25,c:[[1,"Civilization is not sustained by perfect men."],[6,"It is sustained by environments that allow ordinary people to live with dignity."],[14,"Male integrity is not only about men."],[18,"It is one indispensable thread in the fabric of humanity itself."]]}
  ];
var STARTS=[];(function(){var a=0;for(var i=0;i<SCENES.length;i++){STARTS.push(a);a+=SCENES[i].d;}})();