import { makeSprite, flipH } from './pixel.js';
import { makeCanvas } from '../core/screen.js';

// 16x24 overworld walkers. Bodies (rows 0-18) are authored per facing; the four
// leg rows are shared so each direction gets a 3-frame walk cycle for free.
//
// key: o outline  C/c/k cap light/mid/dark   s/S skin   e eye  w eye-white
//      H/h hair    J/j/d jacket light/mid/dark   g pack   p pants  b/B boots

const BODY_DOWN = [
  '................',
  '.....oooooo.....',
  '...oCCcccckko...',
  '...oCccccckko...',
  '...occccccKKo...',
  '..okkkkkkkkkko..',
  '...oHssssssSo...',
  '...osssssssso...',
  '...osweswesSo...',
  '...ossssssSSo...',
  '....oSSSSSSo....',
  '...oJJjjjjdDo...',
  '...oJjjjjjjdo...',
  '...oJjjjjjjdo...',
  '...oJjjjjjddo...',
  '..osjjjjjjjjso..',
  '..oSjjjjjjjjSo..',
  '...oPpppppqqo...',
  '...oPpppppqqo...',
];

const BODY_UP = [
  '................',
  '.....oooooo.....',
  '...oCCcccckko...',
  '...oCccccckko...',
  '...occccccKKo...',
  '..okkkkkkkkkko..',
  '...oHhhhhhhho...',
  '...ohhhhhhhho...',
  '...ohhhhhhhho...',
  '...ohhhhhhhho...',
  '....ohhhhhho....',
  '...oJJjjjjdDo...',
  '...oJjoGGgodo...',
  '...oJjogggodo...',
  '...oJjogggodo...',
  '..osjjjjjjjjso..',
  '..oSjjjjjjjjSo..',
  '...oPpppppqqo...',
  '...oPpppppqqo...',
];

// Facing LEFT; the right-facing set is generated by mirroring.
const BODY_SIDE = [
  '................',
  '....oooooo......',
  '...oCCccckko....',
  '..oCccccckko....',
  '..occccccKKo....',
  '.okkkkkkkkko....',
  '..ossssssHho....',
  '.osssssssHho....',
  '..osweshhho.....',
  '..oSsssshho.....',
  '...oSSSSho......',
  '...oJjjjdo......',
  '..oJjjjjjdo.....',
  '..oJjjjjjgo.....',
  '..oJjjjjjgo.....',
  '.osjjjjjjgo.....',
  '.oSjjjjjjdo.....',
  '..oPppppqo......',
  '..oPppppqo......',
];

const LEGS = {
  stand: [
    '...oPppoppqqo...',
    '...oPppoppqqo...',
    '...oBbboBbbbo...',
    '...obbbobbbbo...',
  ],
  stepA: [
    '...oPppoppqqo...',
    '...oPppoppqqo...',
    '...oBbboppqqo...',
    '...obbbo........',
  ],
  stepB: [
    '...oPppoppqqo...',
    '...oPppoppqqo...',
    '...oPppoBbbbo...',
    '.......obbbbo...',
  ],
};

const LEGS_SIDE = {
  stand: [
    '..oPppppqo......',
    '..oPppppqo......',
    '..oBbbbbbo......',
    '..obbbbbbo......',
  ],
  stepA: [
    '..oPppppqo......',
    '.oPppoppqo......',
    '.oBbbo.oBbbo....',
    '.obbbo.obbbo....',
  ],
  stepB: [
    '..oPppppqo......',
    '..oPpppppqo.....',
    '..oBbbbbbbo.....',
    '..obbbbbbbo.....',
  ],
};

export const PALETTES = {
  player: {
    o: '#1b1424', C: '#f26a52', c: '#d4402f', k: '#9c2418',
    s: '#f2c48e', S: '#c98f5c', e: '#2a1a30', w: '#ffffff',
    H: '#7a5230', h: '#503018',
    J: '#5a90e8', j: '#3868c0', d: '#274a92', g: '#d8b048', G: '#e2c67b',
    p: '#3a3a52', b: '#4a3020', B: '#6b4a2c',
  },
  rival: {
    o: '#1b1424', C: '#b0a8c0', c: '#8a8098', k: '#5e5670',
    s: '#f2c48e', S: '#c98f5c', e: '#2a1a30', w: '#ffffff',
    H: '#e0a040', h: '#b87828',
    J: '#e06a6a', j: '#b83c3c', d: '#8a2828', g: '#40506a', G: '#758193',
    p: '#2e2e40', b: '#3c3020', B: '#5c4a30',
  },
  mom: {
    o: '#1b1424', C: '#f0c8d8', c: '#d89ab0', k: '#a86a84',
    s: '#f5cd9a', S: '#cf9765', e: '#2a1a30', w: '#ffffff',
    H: '#c88a4a', h: '#9a6030',
    J: '#f0e0f0', j: '#d8b8d8', d: '#a888a8', g: '#c0a0c8', G: '#d1bad7',
    p: '#8a5c9c', b: '#5a3a6a', B: '#7a5a8a',
  },
  prof: {
    o: '#1b1424', C: '#e8e8f0', c: '#c8c8d4', k: '#9a9aa8',
    s: '#f2c48e', S: '#c98f5c', e: '#2a1a30', w: '#ffffff',
    H: '#d0d0d8', h: '#a0a0ac',
    J: '#ffffff', j: '#e0e4ec', d: '#b0b8c4', g: '#c0c8d4', G: '#d1d7e0',
    p: '#5a6070', b: '#3a3a48', B: '#585866',
  },
  villager1: {
    o: '#1b1424', C: '#8ad068', c: '#5aa844', k: '#3a7830',
    s: '#e0aa78', S: '#b8804e', e: '#2a1a30', w: '#ffffff',
    H: '#4a3020', h: '#2c1c10',
    J: '#f0d878', j: '#d8b048', d: '#a88028', g: '#a06840', G: '#ba9275',
    p: '#4a5a68', b: '#3a3a30', B: '#5a5a48',
  },
  villager2: {
    o: '#1b1424', C: '#a0c8f0', c: '#6a98d8', k: '#3a68a8',
    s: '#c08a5c', S: '#94643c', e: '#2a1a30', w: '#ffffff',
    H: '#2c1c10', h: '#1a1008',
    J: '#c0c0d0', j: '#9098a8', d: '#68707e', g: '#8a5a3a', G: '#aa8871',
    p: '#5a4a3a', b: '#3a2a1a', B: '#5a4a2a',
  },
  trainer_bug: {
    o: '#1b1424', C: '#f0e0a0', c: '#d8c060', k: '#a89030',
    s: '#f2c48e', S: '#c98f5c', e: '#2a1a30', w: '#ffffff',
    H: '#6a4a20', h: '#48300e',
    J: '#a8d060', j: '#7aa838', d: '#547828', g: '#8a6a30', G: '#aa9369',
    p: '#6a5a30', b: '#4a3a1a', B: '#6a5a2a',
  },
  trainer_hiker: {
    o: '#1b1424', C: '#e09a50', c: '#b87230', k: '#8a5018',
    s: '#e0aa78', S: '#b8804e', e: '#2a1a30', w: '#ffffff',
    H: '#3a2a18', h: '#241a0e',
    J: '#d86a40', j: '#a84a28', d: '#7a3418', g: '#5a6a3a', G: '#889371',
    p: '#4a4a58', b: '#3a2a1a', B: '#5a4a2a',
  },
  elder: {
    o: '#1b1424', C: '#d8d0c0', c: '#b0a898', k: '#807868',
    s: '#e8c098', S: '#b8906a', e: '#2a1a30', w: '#ffffff',
    H: '#e8e8e8', h: '#c0c0c0',
    J: '#8a7a6a', j: '#6a5a4a', d: '#4a3a2a', g: '#8a7a5a', G: '#aa9f88',
    p: '#5a5040', b: '#3a3020', B: '#5a5030',
  },
  nurse: {
    o: '#1b1424', C: '#ffffff', c: '#e8e8f0', k: '#c0c0cc',
    s: '#f5cd9a', S: '#cf9765', e: '#2a1a30', w: '#ffffff',
    H: '#f090b0', h: '#c06888',
    J: '#ffffff', j: '#f0d8e0', d: '#c8a8b8', g: '#e07090', G: '#e898af',
    p: '#e07090', b: '#ffffff', B: '#e0e0e8',
  },
  clerk: {
    o: '#1b1424', C: '#7ab0e8', c: '#4a80c0', k: '#2a5890',
    s: '#e0aa78', S: '#b8804e', e: '#2a1a30', w: '#ffffff',
    H: '#3a2a18', h: '#241a0e',
    J: '#78b0e8', j: '#4a80c0', d: '#2a5890', g: '#d8d8e0', G: '#e2e2e8',
    p: '#2c3a50', b: '#20202c', B: '#40405a',
  },
};

function shift(hex, amt) {
  const v = parseInt(hex.slice(1), 16);
  const f = (c) => {
    const n = amt >= 0 ? c + (255 - c) * amt : c * (1 + amt);
    return Math.max(0, Math.min(255, Math.round(n)));
  };
  return `#${((f((v >> 16) & 255) << 16) | (f((v >> 8) & 255) << 8) | f(v & 255)).toString(16).padStart(6, '0')}`;
}

/** Fill in the derived shadow/highlight tones every palette needs. */
function expand(pal) {
  return {
    ...pal,
    K: pal.K || shift(pal.k, -0.28),
    D: pal.D || shift(pal.d, -0.24),
    q: pal.q || shift(pal.p, -0.28),
    H: pal.HL || shift(pal.s, 0.30),
  };
}

function buildBody(body, legs, pal) {
  const rows = body.concat(legs);
  while (rows.length < 24) rows.push('................');
  return makeSprite(rows, pal);
}

/**
 * Returns { down:[3], up:[3], left:[3], right:[3] } — frame 0 is idle, 1 and 2
 * are the walk poses.
 */
export function buildWalker(palName) {
  const pal = expand(PALETTES[palName] || PALETTES.player);
  const down = [
    buildBody(BODY_DOWN, LEGS.stand, pal),
    buildBody(BODY_DOWN, LEGS.stepA, pal),
    buildBody(BODY_DOWN, LEGS.stepB, pal),
  ];
  const up = [
    buildBody(BODY_UP, LEGS.stand, pal),
    buildBody(BODY_UP, LEGS.stepA, pal),
    buildBody(BODY_UP, LEGS.stepB, pal),
  ];
  const left = [
    buildBody(BODY_SIDE, LEGS_SIDE.stand, pal),
    buildBody(BODY_SIDE, LEGS_SIDE.stepA, pal),
    buildBody(BODY_SIDE, LEGS_SIDE.stepB, pal),
  ];
  const right = left.map(flipH);
  return { down, up, left, right };
}

const cache = new Map();
export function getWalker(palName) {
  if (!cache.has(palName)) cache.set(palName, buildWalker(palName));
  return cache.get(palName);
}

/** Small 8x8 face icon used in the party/summary screens. */
export function makeTrainerFace(palName) {
  const pal = expand(PALETTES[palName] || PALETTES.player);
  const src = buildBody(BODY_DOWN, LEGS.stand, pal);
  const c = makeCanvas(12, 12);
  const g = c.getContext('2d');
  g.imageSmoothingEnabled = false;
  g.drawImage(src, 2, 1, 12, 10, 0, 1, 12, 10);
  return c;
}
